Demo/DemoEasyAccessBS3.3.7/Models/EasyTableModel.cs
using System;
using System.ComponentModel;

namespace DemoEasyAccessBS3._3._7.Models
{
    public class EasyTableModel
    {
        [DisplayName("ID")]
        public string EmployeeId { get; set; }

        [DisplayName("Name")]
        public string EmployeeName { get; set; }

        [DisplayName("Job Title")]
        public string JobTitle { get; set; }
    }
}

Demo/DemoEasyAccessBS3.3.7/Models/ErrorViewModel.cs
using System;

namespace DemoEasyAccessBS3._3._7.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo/DemoEasyAccessBS3.3.7/Controllers/CarouselController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EasyAccessKit.CarouselClass;

namespace DemoEasyAccess.Carousel
{
    public class CarouselController : Controller
    {
        public IActionResult Index()
        {
            List<CarouselItem> items = new List<CarouselItem>();

            CarouselItem item1 = new CarouselItem();
            item1.ImageUrl = "/images/banner1.svg";
            item1.Title = "Image 1";
            item1.SubHeading = "This is the first image";
            item1.AltText = "There is currently no image loaded but this is the alt text to image 1.";

            CarouselItem item2 = new CarouselItem("/images/banner2.svg", "Image 2", "This is image 2", "There is no actual image but this is the image 1 alt text");

            items.Add(item1);
            items.Add(item2);

            return View(items);
        }
    }
}

Demo/DemoEasyAccessBS3.3.7/Controllers/EasyTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DemoEasyAccessBS3._3._7.Models;

namespace DemoEasyAccessBS3._3._7.Controllers
{
    public class EasyTableController : Controller
    {
        public IActionResult Index()
        {
            List<EasyTableModel> models = new List<EasyTableModel>();

            EasyTableModel model1 = new EasyTableModel();
            model1.EmployeeId = "1";
            model1.EmployeeName = "Dan";
            model1.JobTitle = "Manager";
            models.Add(model1);

            return View(models);
        }
    }
}

Demo/DemoEasyAccessBS3.3.7/Controllers/FigureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DemoEasyAccessBS3._3._7.Controllers
{
    public class FigureController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Demo/DemoEasyAccessBS3.3.7/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DemoEasyAccessBS3._3._7.Models;

namespace DemoEasyAccessBS3._3._7.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult DemoExamples()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Demo/DemoEasyAccessBS3.3.7/Controllers/SkipMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DemoEasyAccessBS3._3._7.Controllers
{
    public class SkipMenuController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Demo/DemoEasyAccessBS3.3.7/Views/Carousel/Index.cshtml
@model List<global::EasyAccessKit.CarouselClass.CarouselItem>

@{
    ViewData["Title"] = "Carousel";
}

@EasyAccessKit.Bs3.MainHeading(ViewData["Title"].ToString())

@EasyAccessKit.Bs3.Carousel(Model)

Demo/DemoEasyAccessBS3.3.7/Views/Figure/Index.cshtml
@{
    ViewData["Title"] = "Figure";
}

@EasyAccessKit.Bs3.MainHeading(ViewData["Title"].ToString())

@EasyAccessKit.Bs3.Figure("/images/banner1.svg", "The is the alt tag for this image. It contains a default Microsoft banner", "Above is a default banner Microsoft gives with ASP.NET core projects.")

Demo/DemoEasyAccessBS3.3.7/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
@EasyAccessKit.Bs3.MainHeading(ViewData["Title"].ToString())
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Demo/DemoEasyAccessBS3.3.7/Views/Home/DemoExamples.cshtml
@{
    ViewData["Title"] = "Demo Examples";
}

@EasyAccessKit.Bs3.MainHeading(ViewData["Title"].ToString())

<p>Currently this is just where to just to test out the EasyAccessKit. Nothing is set in stone here.</p>
<ul>
    <li><a asp-controller="SkipMenu"
   asp-action="Index">Skip Menus</a></li>
    <li>
        <a asp-controller="EasyTable"
           asp-action="Index">Easy Table</a>
    </li>
    <li>
        <a asp-controller="Carousel"
           asp-action="Index">Carousel</a>
    </li>
</ul>

Demo/DemoEasyAccessBS3.3.7/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@EasyAccessKit.Bs3.HiddenMainHeading(ViewData["Title"].ToString())

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Demo/DemoEasyAccessBS3.3.7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoEasyAccessBS3._3._7</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @EasyAccessKit.Bs3.SkipMenu()
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DemoEasyAccessBS3._3._7</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="DemoExamples">Demo Examples</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - DemoEasyAccessBS3._3._7</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Demo/DemoEasyAccessBS3.3.7/Views/SkipMenu/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@EasyAccessKit.Bs3.MainHeading("Skip Menus")

<p>To use the skip menu, simply use the <code>SkipMenu()</code> method in the Layout of your application. Place it after the body element in the layout and you should be good.</p>
<p>Even though you can't see it, skip menus can help people who use assistive devices achieve what they want in a page faster. 
    A skip menu is usually a invisible menu that is found by the first tab input the web page gets. When an assistive device goes over it, the device will let the 
    user know it is a specifically made menu for them. The alternative to that is you have the correct heading index (start with h1) and the person using the assistive
    device will navigate to the first heading. Either way, it leads us to the heading methods in the EasyAccessKit.
    </p>

<h2>Main Heading</h2>
<p>The <code>MainHeading()</code> method is set in place to easily make a heading that the skip menu can link to and is set to be an h1 element.
    This way the person using the assistive device will be able to know where to start either way they navigate to the main content, as stated above in the introduction.</p>
<p>To view more about the <code>MainHeading()</code> method, please visit the documentation for the EasyAccessKit.</p>

<h2>Hidden Main Heading</h2>
<p>
    The <code>HiddenMainHeading()</code> method is for pages that don't need a heading. Putting an invisible heading into the browser will help the person 
    using the assistive device to move to the content you want them to focus on. It's the same as the <code>MainHeading()</code> but you can't see it.
</p>
<p>To view more about the <code>HiddenMainHeading()</code> method, please visit the documentation for the EasyAccessKit.</p>